import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "../../../../../utils/api";

const FindBuildsPage: NextPage = () => {
  const { opponentRace, raceName } = useRouter().query as {
    opponentRace: string;
    raceName: string;
  };

  const builds = api.builds.getBuildsByMatchUp.useQuery({
    matchUp: `${raceName.toLowerCase().charAt(0)}v${opponentRace
      .toLowerCase()
      .charAt(0)}`,
  });

  console.log(builds);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-8 text-black dark:bg-gray-800 dark:text-white">
        {raceName} vs {opponentRace}
      </main>
    </>
  );
};

export default FindBuildsPage;
