import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { RaceCard } from "../../../races";

const FindBuildsPage: NextPage = () => {
  const raceName = useRouter().query.raceName;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-8 text-black dark:bg-gray-800 dark:text-white">
        <section className="flex flex-col gap-4 text-center">
          <p>{raceName}</p>
          <p>VS.</p>
          <p>Select Opponent&apos;s Race</p>
        </section>

        <ul className="flex gap-20">
          <li>
            <RaceCard
              href={`/races/${raceName}/match-ups/zerg`}
              raceImageSrc={"/zerg.jpeg"}
              raceName="Zerg"
              isOpponent
            />
          </li>
          <li>
            <RaceCard
              href={`/races/${raceName}/match-ups/terran`}
              raceImageSrc={"/terran.jpeg"}
              raceName="Terran"
              isOpponent
            />
          </li>
          <li>
            <RaceCard
              href={`/races/${raceName}/match-ups/protoss`}
              raceImageSrc={"/protoss.jpeg"}
              raceName="Protoss"
              isOpponent
            />
          </li>
        </ul>

        {/* <Link href="/submit-build">View Builds</Link>
        <Link href="/builds">View Builds</Link>
        <Link href="/builds">View Builds</Link> */}
      </main>
    </>
  );
};

export default FindBuildsPage;
